[project]
name = "hsi-2025-cir"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "paddleocr>=3.3.1",
    "paddlepaddle==3.2.0",
    "torch>=2.9.0",
    "transformers>=4.57.1",
]
